// <auto-generated />
using System;
using EmployeeAttendanceTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAttendanceTracker.Migrations
{
    [DbContext(typeof(EmployeeADContext))]
    [Migration("20240511194719_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalExam.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbsDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Excused")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Hours")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Absences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbsDate = new DateTime(1998, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Excused = "Y",
                            Hours = 4f
                        },
                        new
                        {
                            Id = 2,
                            AbsDate = new DateTime(1998, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            Excused = "Y",
                            Hours = 8f
                        },
                        new
                        {
                            Id = 3,
                            AbsDate = new DateTime(1998, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Excused = "N",
                            Hours = 8f
                        },
                        new
                        {
                            Id = 4,
                            AbsDate = new DateTime(1998, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            Excused = "N",
                            Hours = 8f
                        },
                        new
                        {
                            Id = 5,
                            AbsDate = new DateTime(1998, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 8,
                            Excused = "Y",
                            Hours = 8f
                        },
                        new
                        {
                            Id = 6,
                            AbsDate = new DateTime(1998, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 9,
                            Excused = "N",
                            Hours = 2f
                        },
                        new
                        {
                            Id = 7,
                            AbsDate = new DateTime(1999, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 12,
                            Excused = "N",
                            Hours = 8f
                        },
                        new
                        {
                            Id = 8,
                            AbsDate = new DateTime(1999, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 20,
                            Excused = "Y",
                            Hours = 4f
                        });
                });

            modelBuilder.Entity("FinalExam.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1980, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepName = "Alex",
                            EmployeeId = 3
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1984, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepName = "Alice",
                            EmployeeId = 3
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1989, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepName = "Biff",
                            EmployeeId = 8
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1987, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepName = "Billy",
                            EmployeeId = 8
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1985, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepName = "Butch",
                            EmployeeId = 8
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1986, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepName = "Heather",
                            EmployeeId = 22
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1986, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepName = "Holly",
                            EmployeeId = 22
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1983, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepName = "Mary",
                            EmployeeId = 27
                        });
                });

            modelBuilder.Entity("FinalExam.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Add1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Add2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Add1 = "543 Rosetta Avenue",
                            Add2 = "",
                            City = "Florissant",
                            DeptCode = "MK",
                            FirstName = "Paul",
                            HireDate = new DateTime(1986, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Plodder",
                            Phone = "314-837-9610",
                            State = "MO",
                            Zip = "63031"
                        },
                        new
                        {
                            Id = 2,
                            Add1 = "4652 Blue Willow",
                            Add2 = "",
                            City = "Imperial",
                            DeptCode = "CL",
                            FirstName = "George",
                            HireDate = new DateTime(1990, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Arfuss",
                            Phone = "314-942-3153",
                            State = "MO",
                            Zip = "63052"
                        },
                        new
                        {
                            Id = 3,
                            Add1 = "3229 Highland Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Tom",
                            HireDate = new DateTime(1989, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "ADM",
                            LastName = "Turtle",
                            Phone = "314-781-0402",
                            State = "MO",
                            Zip = "63139"
                        },
                        new
                        {
                            Id = 4,
                            Add1 = "0520 Ashbrook Drive",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "William",
                            HireDate = new DateTime(1987, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SRA",
                            LastName = "Jones",
                            Phone = "314-868-4412",
                            State = "MO",
                            Zip = "63027"
                        },
                        new
                        {
                            Id = 5,
                            Add1 = "32 Fenway",
                            Add2 = "",
                            City = "Ferguson",
                            DeptCode = "MK",
                            FirstName = "John",
                            HireDate = new DateTime(1991, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "MKM",
                            LastName = "Jones",
                            Phone = "314-522-0861",
                            State = "MO",
                            Zip = "63135"
                        },
                        new
                        {
                            Id = 6,
                            Add1 = "1226 Rio Silva Place",
                            Add2 = "Apt. H",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Anthony",
                            HireDate = new DateTime(1988, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "CLE",
                            LastName = "Jones",
                            Phone = "314-431-1578",
                            State = "MO",
                            Zip = "63111"
                        },
                        new
                        {
                            Id = 7,
                            Add1 = "442 Brotherton Lane",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Kyle",
                            HireDate = new DateTime(1992, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "CLE",
                            LastName = "Jones",
                            Phone = "314-522-3623",
                            State = "MO",
                            Zip = "63135"
                        },
                        new
                        {
                            Id = 8,
                            Add1 = "3228 Edison Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Kelley",
                            HireDate = new DateTime(1987, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Berty",
                            Phone = "314-781-8798",
                            State = "MO",
                            Zip = "63121"
                        },
                        new
                        {
                            Id = 9,
                            Add1 = "6520 Lincoln Park West",
                            Add2 = "",
                            City = "Chicago",
                            DeptCode = "MK",
                            FirstName = "George",
                            HireDate = new DateTime(1986, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "MacElroy",
                            Phone = "312-748-7817",
                            State = "IL",
                            Zip = "54614"
                        },
                        new
                        {
                            Id = 10,
                            Add1 = "1234 Paule Drive",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "James",
                            HireDate = new DateTime(1990, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "JRA",
                            LastName = "McDunnel",
                            Phone = "314-831-6826",
                            State = "MO",
                            Zip = "63125"
                        },
                        new
                        {
                            Id = 11,
                            Add1 = "5417 Lone Elm Drive.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "Thomas",
                            HireDate = new DateTime(1994, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "ACM",
                            LastName = "McDunnel",
                            Phone = "314-467-6937",
                            State = "MO",
                            Zip = "63125"
                        },
                        new
                        {
                            Id = 12,
                            Add1 = "1244 South Broadway",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Thomas",
                            HireDate = new DateTime(1988, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Smith",
                            Phone = "314-354-1446",
                            State = "MO",
                            Zip = "63111"
                        },
                        new
                        {
                            Id = 13,
                            Add1 = "8725 McKinley Road",
                            Add2 = "",
                            City = "Joplin",
                            DeptCode = "CL",
                            FirstName = "Martin",
                            HireDate = new DateTime(1987, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Jukes",
                            Phone = "314-933-2903",
                            State = "MO",
                            Zip = "63119"
                        },
                        new
                        {
                            Id = 14,
                            Add1 = "4340 A Watson Road",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "SL",
                            FirstName = "August",
                            HireDate = new DateTime(1990, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Smith",
                            Phone = "314-262-1105",
                            State = "MO",
                            Zip = "63119"
                        },
                        new
                        {
                            Id = 15,
                            Add1 = "21318 Parsons Blvd.",
                            Add2 = "",
                            City = "Flushing",
                            DeptCode = "SL",
                            FirstName = "Richard",
                            HireDate = new DateTime(1990, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Arfuss",
                            Phone = "618-922-0987",
                            State = "IL",
                            Zip = "54355"
                        },
                        new
                        {
                            Id = 16,
                            Add1 = "12 Manson Avenue",
                            Add2 = "",
                            City = "St. Peters",
                            DeptCode = "AC",
                            FirstName = "Sean",
                            HireDate = new DateTime(1987, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SRA",
                            LastName = "Arfuss",
                            Phone = "314-721-3338",
                            State = "MO",
                            Zip = "63376"
                        },
                        new
                        {
                            Id = 17,
                            Add1 = "1530 Watson Road",
                            Add2 = "Lot #15",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Arthur",
                            HireDate = new DateTime(1986, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Mueller",
                            Phone = "314-849-4515",
                            State = "MO",
                            Zip = "63127"
                        },
                        new
                        {
                            Id = 18,
                            Add1 = "1201 Crestshire Lane",
                            Add2 = "",
                            City = "St. Ann",
                            DeptCode = "CL",
                            FirstName = "James",
                            HireDate = new DateTime(1993, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Miller",
                            Phone = "314-427-3557",
                            State = "MO",
                            Zip = "63121"
                        },
                        new
                        {
                            Id = 19,
                            Add1 = "4311 B. Alfred Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Daniel",
                            HireDate = new DateTime(1988, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Mueller",
                            Phone = "314-773-4463",
                            State = "MO",
                            Zip = "63110"
                        },
                        new
                        {
                            Id = 20,
                            Add1 = "431 Monteith Circle",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "Michael",
                            HireDate = new DateTime(1989, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "JRA",
                            LastName = "Milkwagin",
                            Phone = "314-867-1131",
                            State = "MO",
                            Zip = "63137"
                        },
                        new
                        {
                            Id = 21,
                            Add1 = "8712 Oakland",
                            Add2 = "Apt 205",
                            City = "Oakland",
                            DeptCode = "SL",
                            FirstName = "Michael",
                            HireDate = new DateTime(1987, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SMN",
                            LastName = "Neuner",
                            Phone = "314-645-7773",
                            State = "MO",
                            Zip = "63139"
                        },
                        new
                        {
                            Id = 22,
                            Add1 = "5430 Queeney Ave.",
                            Add2 = "",
                            City = "Sauget",
                            DeptCode = "SL",
                            FirstName = "Kenn",
                            HireDate = new DateTime(1988, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Ortega",
                            Phone = "314-386-5776",
                            State = "IL",
                            Zip = "54206"
                        },
                        new
                        {
                            Id = 23,
                            Add1 = "4876 Gallant Fox Drive",
                            Add2 = "",
                            City = "Florissant",
                            DeptCode = "AC",
                            FirstName = "Phil",
                            HireDate = new DateTime(1989, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "JRA",
                            LastName = "Will",
                            Phone = "314-831-4416",
                            State = "MO",
                            Zip = "63033"
                        },
                        new
                        {
                            Id = 24,
                            Add1 = "341 Imperial Lane",
                            Add2 = "",
                            City = "Fenton",
                            DeptCode = "MK",
                            FirstName = "Sally",
                            HireDate = new DateTime(1989, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Sellum",
                            Phone = "314-343-1992",
                            State = "MO",
                            Zip = "63026"
                        },
                        new
                        {
                            Id = 25,
                            Add1 = "5447 Astoria Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Barney",
                            HireDate = new DateTime(1986, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Varfuss",
                            Phone = "314-868-5218",
                            State = "MO",
                            Zip = "63137"
                        },
                        new
                        {
                            Id = 26,
                            Add1 = "6515 Bischoff Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "SL",
                            FirstName = "Joseph",
                            HireDate = new DateTime(1991, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Tummyfill",
                            Phone = "314-865-3739",
                            State = "Mo",
                            Zip = "63110"
                        },
                        new
                        {
                            Id = 27,
                            Add1 = "Box 33 Rt. #7",
                            Add2 = "",
                            City = "New Douglas",
                            DeptCode = "AC",
                            FirstName = "Steve",
                            HireDate = new DateTime(1991, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SRA",
                            LastName = "Rockford",
                            Phone = "217-456-6376",
                            State = "IL",
                            Zip = "54074"
                        },
                        new
                        {
                            Id = 28,
                            Add1 = "312 Bellerive Acres",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Daniel",
                            HireDate = new DateTime(1987, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "CLE",
                            LastName = "Daly",
                            Phone = "314-389-2339",
                            State = "MO",
                            Zip = "63121"
                        },
                        new
                        {
                            Id = 29,
                            Add1 = "3214 Loughborough Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Salvatore",
                            HireDate = new DateTime(1989, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Malt",
                            Phone = "314-352-3347",
                            State = "MO",
                            Zip = "63109"
                        },
                        new
                        {
                            Id = 30,
                            Add1 = "2155 Ripple St.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Thomas",
                            HireDate = new DateTime(1991, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "CLE",
                            LastName = "Smith",
                            Phone = "314-644-2765",
                            State = "MO",
                            Zip = "63139"
                        },
                        new
                        {
                            Id = 31,
                            Add1 = "654 Albert Ave",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "SL",
                            FirstName = "Richard",
                            HireDate = new DateTime(1988, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Smythe",
                            Phone = "314-822-3561",
                            State = "MO",
                            Zip = "63122"
                        },
                        new
                        {
                            Id = 32,
                            Add1 = "7864 Queeney Ave.",
                            Add2 = "",
                            City = "Sauget",
                            DeptCode = "SL",
                            FirstName = "Thomas",
                            HireDate = new DateTime(1986, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Smiley",
                            Phone = "618-337-6451",
                            State = "IL",
                            Zip = "54206"
                        },
                        new
                        {
                            Id = 33,
                            Add1 = "2312 Graham Street",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "George",
                            HireDate = new DateTime(1990, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "JRA",
                            LastName = "Rockford",
                            Phone = "314-644-5926",
                            State = "MO",
                            Zip = "63139"
                        },
                        new
                        {
                            Id = 34,
                            Add1 = "657 Bella Lane",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Jeffrey",
                            HireDate = new DateTime(1989, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Fawlty",
                            Phone = "314-867-4474",
                            State = "MO",
                            Zip = "63137"
                        },
                        new
                        {
                            Id = 35,
                            Add1 = "3449 Arsenal St.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "SL",
                            FirstName = "Daniel",
                            HireDate = new DateTime(1986, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Steadman",
                            Phone = "314-772-0772",
                            State = "MO",
                            Zip = "63118"
                        },
                        new
                        {
                            Id = 36,
                            Add1 = "7837 Walsh Street",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "SL",
                            FirstName = "Gregory",
                            HireDate = new DateTime(1991, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Jones",
                            Phone = "314-351-0984",
                            State = "MO",
                            Zip = "63116"
                        },
                        new
                        {
                            Id = 37,
                            Add1 = "1242 Meramec Street",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "SL",
                            FirstName = "Gregory",
                            HireDate = new DateTime(1991, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Eliot",
                            Phone = "314-752-0287",
                            State = "MO",
                            Zip = "63118"
                        },
                        new
                        {
                            Id = 38,
                            Add1 = "5444 Walsh Street",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Jeffrey",
                            HireDate = new DateTime(1985, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Willow",
                            Phone = "314-352-4678",
                            State = "MO",
                            Zip = "63116"
                        },
                        new
                        {
                            Id = 39,
                            Add1 = "8938 Leona Street",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "Robert",
                            HireDate = new DateTime(1988, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "JRA",
                            LastName = "Stiner",
                            Phone = "314-752-1712",
                            State = "MO",
                            Zip = "63116"
                        },
                        new
                        {
                            Id = 40,
                            Add1 = "3246 Buddie Drive",
                            Add2 = "",
                            City = "Hazelwood",
                            DeptCode = "CL",
                            FirstName = "Lawrence",
                            HireDate = new DateTime(1987, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "CLE",
                            LastName = "Nessman",
                            Phone = "314-524-3344",
                            State = "MO",
                            Zip = "63042"
                        },
                        new
                        {
                            Id = 41,
                            Add1 = "148 Highland Ave.",
                            Add2 = "",
                            City = "Kirkwood",
                            DeptCode = "CL",
                            FirstName = "Robert",
                            HireDate = new DateTime(1988, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Sulley",
                            Phone = "314-822-3468",
                            State = "MO",
                            Zip = "63122"
                        },
                        new
                        {
                            Id = 42,
                            Add1 = "1641 Atmore Drive.",
                            Add2 = "",
                            City = "Ferguson",
                            DeptCode = "CL",
                            FirstName = "Leonard",
                            HireDate = new DateTime(1985, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Birdwall",
                            Phone = "314-869-1243",
                            State = "MO",
                            Zip = "63136"
                        },
                        new
                        {
                            Id = 43,
                            Add1 = "612 Berry Road",
                            Add2 = "P.O. Box 121",
                            City = "Woodriver",
                            DeptCode = "SL",
                            FirstName = "Terry",
                            HireDate = new DateTime(1986, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Kubick",
                            Phone = "618-259-0855",
                            State = "IL",
                            Zip = "54095"
                        },
                        new
                        {
                            Id = 44,
                            Add1 = "5643 Osceola Street",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "James",
                            HireDate = new DateTime(1987, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Webster",
                            Phone = "314-353-4335",
                            State = "MO",
                            Zip = "63111"
                        },
                        new
                        {
                            Id = 45,
                            Add1 = "3250  Hiawatha Ave.",
                            Add2 = "",
                            City = "St.Louis",
                            DeptCode = "AC",
                            FirstName = "Arthur",
                            HireDate = new DateTime(1990, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SRA",
                            LastName = "Waffles",
                            Phone = "314-781-1285",
                            State = "MO",
                            Zip = "63117"
                        },
                        new
                        {
                            Id = 46,
                            Add1 = "8765 Tower Grove Place",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Merrell",
                            HireDate = new DateTime(1990, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "CLE",
                            LastName = "Varfuss",
                            Phone = "314-773-2917",
                            State = "MO",
                            Zip = "63110"
                        },
                        new
                        {
                            Id = 47,
                            Add1 = "314 Porchester Drive",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "James",
                            HireDate = new DateTime(1989, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Williams",
                            Phone = "314-544-9268",
                            State = "MO",
                            Zip = "63125"
                        },
                        new
                        {
                            Id = 48,
                            Add1 = "876 Mildred Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "Robert",
                            HireDate = new DateTime(1988, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "JRA",
                            LastName = "Walleye",
                            Phone = "314-962-4569",
                            State = "MO",
                            Zip = "63119"
                        },
                        new
                        {
                            Id = 49,
                            Add1 = "438 Highland Drive",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Kenny",
                            HireDate = new DateTime(1985, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Feltz",
                            Phone = "314-487-9555",
                            State = "MO",
                            Zip = "63129"
                        },
                        new
                        {
                            Id = 50,
                            Add1 = "5430 Roxbury Drive",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Andrew",
                            HireDate = new DateTime(1985, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Varfuss",
                            Phone = "314-487-2181",
                            State = "MO",
                            Zip = "63125"
                        },
                        new
                        {
                            Id = 51,
                            Add1 = "8704 Edwards Road",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "Terry",
                            HireDate = new DateTime(1990, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "JRA",
                            LastName = "Fitzgerald",
                            Phone = "314-487-4933",
                            State = "MO",
                            Zip = "63125"
                        },
                        new
                        {
                            Id = 52,
                            Add1 = "8122 Richman Place",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "Lawrence",
                            HireDate = new DateTime(1989, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SRA",
                            LastName = "Winer",
                            Phone = "314-647-6692",
                            State = "MO",
                            Zip = "63143"
                        },
                        new
                        {
                            Id = 53,
                            Add1 = "Box 654 R.R.#1",
                            Add2 = "",
                            City = "Millstadt",
                            DeptCode = "SL",
                            FirstName = "Steve",
                            HireDate = new DateTime(1986, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Maverick",
                            Phone = "618-476-3398",
                            State = "IL",
                            Zip = "54260"
                        },
                        new
                        {
                            Id = 54,
                            Add1 = "3402 Davison",
                            Add2 = "",
                            City = "Clayton",
                            DeptCode = "SL",
                            FirstName = "Karl",
                            HireDate = new DateTime(1990, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SLS",
                            LastName = "Kong",
                            Phone = "314-721-2334",
                            State = "MO",
                            Zip = "63105"
                        },
                        new
                        {
                            Id = 55,
                            Add1 = "7679 Schollmeyer Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "AC",
                            FirstName = "Joseph",
                            HireDate = new DateTime(1990, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "JRA",
                            LastName = "Wiliams",
                            Phone = "314-481-7091",
                            State = "MO",
                            Zip = "63109"
                        },
                        new
                        {
                            Id = 56,
                            Add1 = "654 Duchess Ct.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "MK",
                            FirstName = "Jules",
                            HireDate = new DateTime(1988, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Billiard",
                            Phone = "314-838-1571",
                            State = "MO",
                            Zip = "63131"
                        },
                        new
                        {
                            Id = 57,
                            Add1 = "143 Willowcreek",
                            Add2 = "",
                            City = "Edwardsville",
                            DeptCode = "MK",
                            FirstName = "Michael",
                            HireDate = new DateTime(1989, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "EDT",
                            LastName = "Smith",
                            Phone = "618-656-4444",
                            State = "IL",
                            Zip = "54026"
                        },
                        new
                        {
                            Id = 58,
                            Add1 = "5321 Lloyd Ave.",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Joseph",
                            HireDate = new DateTime(1990, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "CLE",
                            LastName = "Jones",
                            Phone = "314-644-2278",
                            State = "MO",
                            Zip = "63139"
                        },
                        new
                        {
                            Id = 59,
                            Add1 = "45 Main Street",
                            Add2 = "",
                            City = "St. Peters",
                            DeptCode = "CL",
                            FirstName = "James",
                            HireDate = new DateTime(1991, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Caline",
                            Phone = "314-962-4344",
                            State = "MO",
                            Zip = "63376"
                        },
                        new
                        {
                            Id = 60,
                            Add1 = "5655 Morganford Road",
                            Add2 = "",
                            City = "Oakland",
                            DeptCode = "CL",
                            FirstName = "Kevin",
                            HireDate = new DateTime(1985, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Plodder",
                            Phone = "314-771-3377",
                            State = "MO",
                            Zip = "63116"
                        },
                        new
                        {
                            Id = 61,
                            Add1 = "4000 Ashbrook",
                            Add2 = "",
                            City = "St. Louis",
                            DeptCode = "AC",
                            FirstName = "Kim",
                            HireDate = new DateTime(1987, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobCode = "SEC",
                            LastName = "Taylor",
                            Phone = "314-868-9876",
                            State = "MO",
                            Zip = "63137"
                        });
                });

            modelBuilder.Entity("FinalExam.Absence", b =>
                {
                    b.HasOne("FinalExam.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FinalExam.Dependent", b =>
                {
                    b.HasOne("FinalExam.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
